import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Apple Watch Hermes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/3e3390c446.js" crossorigin="anonymous"></script>
      </Head>

      <main className={styles.main}>
        <h6 style={{fontWeight:'100', fontSize:'.8rem', padding:'0', margin:'0'}}>LIMITED EDITION PARIS</h6>
        <h2 style={{fontWeight:'600'}}>Apple Watch Hermes</h2>
      </main>
      <div style={{textAlign:'center', fontSize:'15rem', color:'white', fontWeight:'700', zIndex:'-99999999'}}>
        <h1>HERMES</h1>
        <div style={{display:'flex', alignItems:'center', zIndex:'9'}}>
        <Image src={'/watch.png'} width={480} height={480} />
        </div>
      </div>

      <nav>
        <ul>
          <li>Classic</li>
          <li>Sport</li>
          <li>Premium</li>
        </ul>
      </nav>
      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
